import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { PlaybackBar } from "./components/PlaybackBar";
import { getDb } from "@/lib/db";
import { getUser } from "@/lib/user";
import { PlaybackContextProvider } from "./components/PlaybackContextProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const db = getDb();
    const userId = await getUser();

    const randomSongs = await db
        .selectFrom("songs")
        .innerJoin("albums", "songs.album_id", "albums.id")
        .innerJoin("authors", "albums.author_id", "authors.id")
        .select([
            "songs.id",
            "songs.name",
            "authors.name as author",
            "songs.duration",
        ])
        .limit(10)
        .execute();

    const playlists = await db
        .selectFrom("playlists")
        .select(["playlists.id", "playlists.name"])
        .where("playlists.user_id", "=", userId)
        .execute();

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <PlaybackContextProvider initialSongs={randomSongs}>
                    <Navbar />
                    {children}
                    <div className="fixed h-24 bg-base-100 bottom-0 left-0 right-0 border-t border-base-300">
                        <PlaybackBar
                            userId={userId}
                            songs={randomSongs}
                            playlists={playlists}
                        />
                    </div>
                </PlaybackContextProvider>
            </body>
        </html>
    );
}
